"use client";
import { useMemo, useRef, useState } from "react";
import { motion, useReducedMotion, useScroll, useTransform } from "motion/react";
import { Reveal } from "@/components/animations/Reveal";
import { ButtonLink } from "@/components/ui/ButtonLink";

const capabilities=[
 ["Answers Questions","Accurate answers grounded in your business information."],["Captures Leads","Collects contact details while intent is high."],["Books Appointments","Moves qualified visitors toward your calendar."],["English + Spanish","Communicates naturally in the customer’s language."],["Human Handoff","Escalates when a conversation needs your team."],["Conversation Analytics","Shows what visitors ask and where they convert."],["Instant Notifications","Alerts the right person when a lead is ready."],["CRM Integrations","Prepared to connect with the systems you already use."],["Automations","Triggers follow-up workflows without repetitive admin work."],
];
const story=["A visitor arrives after hours.","MateAI answers instantly.","It understands the service they need.","It captures their phone number.","It offers the next available appointment.","Your business receives a qualified lead."];

export function ProblemSection(){return <section className="section problem-section"><Reveal><span className="section-kicker">The response gap</span><h2>Your website is open 24/7.<br/><span>Your team isn&apos;t.</span></h2></Reveal><div className="problem-grid">{[["01","Missed Leads","Visitors leave when nobody answers."],["02","Slow Responses","The first business to respond often wins the customer."],["03","After-Hours Opportunities","Prospects search at night, on weekends, and during holidays."]].map((item,index)=><Reveal className="problem-item" delay={index*.08} key={item[1]}><b>{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p></Reveal>)}</div><Reveal className="problem-answer"><span>MateAI</span> responds instantly — every time.</Reveal></section>}

export function StorySection(){const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:["start start","end end"]});const progress=useTransform(scrollYProgress,[0,1],[0,100]);return <section className="story" ref={ref} id="how-it-works"><div className="story-sticky"><div className="story-copy"><span className="section-kicker light">A lead, captured end to end</span><h2>Your website works 24/7.<br/>Now your receptionist does too.</h2><div className="story-progress"><motion.i style={{width:reduced?"100%":progress}}/></div></div><div className="story-device"><div className="mini-browser"><div className="browser-bar"><i/><i/><i/><span>yourbusiness.com</span></div><div className="browser-content"><div className="business-placeholder"><span>LOCAL SERVICE CO.</span><h3>How can we help today?</h3></div><div className="story-chat">{story.map((text,index)=><StoryItem key={text} text={text} index={index} progress={scrollYProgress} reduced={Boolean(reduced)}/>)}</div></div></div></div></div></section>}
function StoryItem({text,index,progress,reduced}:{text:string;index:number;progress:ReturnType<typeof useScroll>["scrollYProgress"];reduced:boolean}){const opacity=useTransform(progress,[index/7,(index+1)/7],[0,1]);const y=useTransform(progress,[index/7,(index+1)/7],[16,0]);return <motion.div style={reduced?undefined:{opacity,y}}><span>{String(index+1).padStart(2,"0")}</span>{text}</motion.div>}

export function Capabilities(){return <section className="section" id="solutions"><Reveal><span className="section-kicker">One connected system</span><h2>One AI receptionist.<br/><span>Multiple jobs.</span></h2><p className="section-intro">From the first question to a booked appointment, MateAI keeps the customer moving.</p></Reveal><div className="capability-list">{capabilities.map(([title,body],index)=><Reveal className="capability-row" key={title} delay={(index%3)*.04}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p><i>↗</i></Reveal>)}</div></section>}

export function HowItWorks(){return <section className="section how-section"><Reveal><span className="section-kicker">Simple launch</span><h2>Get your AI receptionist<br/><span>in four steps.</span></h2></Reveal><div className="steps">{[["01","We Learn Your Business","Services, service area, hours, FAQs, and lead qualification."],["02","We Build Your AI","A receptionist configured around how your business actually works."],["03","We Install It","A lightweight widget is added to your existing website."],["04","Start Capturing Leads","Visitors get answers and your team receives organized opportunities."]].map((s,i)=><Reveal className="step" key={s[0]} delay={i*.07}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></Reveal>)}</div><Reveal className="no-website"><strong>No new website required.</strong><span>MateAI installs with a small script on the site you already own.</span><code>&lt;script src=&quot;mateai.js&quot; async&gt;&lt;/script&gt;</code></Reveal></section>}

export function BeforeAfter(){return <section className="section comparison"><Reveal><span className="section-kicker">Same visitor. Different outcome.</span><h2>Before MateAI.<br/><span>After MateAI.</span></h2></Reveal><div className="comparison-grid"><Timeline title="Without MateAI" tone="muted" items={["10:47 PM — Customer visits","No response","Visitor leaves","Calls a competitor","Lost lead"]}/><Timeline title="With MateAI" tone="active" items={["10:47 PM — Customer visits","AI responds instantly","Answers the question","Captures phone number","Books an appointment"]}/></div></section>}
function Timeline({title,tone,items}:{title:string;tone:string;items:string[]}){return <Reveal className={`timeline ${tone}`}><h3>{title}</h3>{items.map((item,index)=><div key={item}><i>{index+1}</i><span>{item}</span></div>)}</Reveal>}

export function DashboardPreview(){return <section className="section dashboard-section"><Reveal><span className="section-kicker">Know what happens next</span><h2>Every conversation becomes<br/><span>organized customer intent.</span></h2><p className="section-intro">Sample interface and demo data shown for product visualization.</p></Reveal><Reveal className="dashboard"><div className="dash-sidebar"><b>M</b>{["Overview","Leads","Conversations","Appointments","Insights"].map(x=><span className={x==="Overview"?"active":""} key={x}>{x}</span>)}</div><div className="dash-main"><div className="dash-head"><div><small>DEMO WORKSPACE</small><h3>Good morning, Alex.</h3></div><button>Last 30 days⌄</button></div><div className="metric-grid">{[["Today’s Leads","12","+18%"],["Conversations","47","+9%"],["Appointments","8","+24%"],["Conversion Rate","31%","Demo"]].map(m=><div key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small>{m[2]}</small></div>)}</div><div className="dash-bottom"><div className="lead-table"><h4>Recent leads <span>Sample data</span></h4>{[["JS","John Smith","Roof Inspection","New"],["AB","Ashley Brown","Roof Replacement","Contacted"],["MJ","Mike Jones","Storm Damage","Booked"]].map(r=><div key={r[1]}><i>{r[0]}</i><strong>{r[1]}</strong><span>{r[2]}</span><b>{r[3]}</b></div>)}</div><div className="chart"><h4>Lead activity</h4><div className="bars">{[40,64,48,80,62,91,73,86,56,95,72,88].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></div></div></Reveal></section>}

export function Integrations(){const items=[["Google Calendar","Coming Soon"],["Calendly","Custom Integration"],["HubSpot","Custom Integration"],["GoHighLevel","Custom Integration"],["n8n","Available"],["Make","Coming Soon"],["Zapier","Coming Soon"],["Email","Available"],["SMS","Custom Integration"],["Webhooks + APIs","Available"]];return <section className="section integrations"><Reveal><span className="section-kicker">Built to connect</span><h2>Works with your<br/><span>existing tools.</span></h2></Reveal><div className="integration-track">{items.map(([name,status])=><div key={name}><strong>{name}</strong><span className={status.toLowerCase().replaceAll(" ","-")}>{status}</span></div>)}</div></section>}

export function RoiCalculator(){const [visitors,setVisitors]=useState(1000);const [value,setValue]=useState(300);const [leads,setLeads]=useState(12);const [close,setClose]=useState(25);const revenue=useMemo(()=>Math.round(leads*(close/100)*value),[leads,close,value]);return <section className="section roi"><Reveal><span className="section-kicker">Model the opportunity</span><h2>What could faster response<br/><span>be worth?</span></h2></Reveal><div className="roi-shell"><div className="roi-inputs"><Range label="Monthly Website Visitors" value={visitors} set={setVisitors} min={100} max={10000} step={100}/><Range label="Average Customer Value" value={value} set={setValue} min={50} max={5000} step={50} prefix="$"/><Range label="Additional Leads" value={leads} set={setLeads} min={1} max={100}/><Range label="Closing Rate" value={close} set={setClose} min={1} max={100} suffix="%"/></div><div className="roi-result"><small>POTENTIAL ADDITIONAL REVENUE</small><motion.strong key={revenue} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}>${revenue.toLocaleString()}<span>/mo</span></motion.strong><p>Based on {leads} additional leads at a {close}% close rate.</p><em>Estimate only. Actual results vary.</em></div></div></section>}
function Range({label,value,set,min,max,step=1,prefix="",suffix=""}:{label:string;value:number;set:(v:number)=>void;min:number;max:number;step?:number;prefix?:string;suffix?:string}){return <label><span>{label}<b>{prefix}{value.toLocaleString()}{suffix}</b></span><input type="range" value={value} onChange={e=>set(Number(e.target.value))} min={min} max={max} step={step}/></label>}

export function FinalCta(){return <section className="final-cta"><div className="final-glow"/><Reveal><span className="section-kicker light">The next lead is already looking</span><h2>Your next customer could be<br/>on your website right now.</h2><p>Make sure someone is there to answer.</p><div><ButtonLink href="/book-demo">Book a Free Demo</ButtonLink><ButtonLink href="/demo" variant="ghost">Try MateAI</ButtonLink></div></Reveal></section>}
