"use client";
import { useState } from "react";
import Link from "next/link";
import { pricingPlans, type PricingPlan } from "@/config/pricing";
import { getPaddle } from "@/lib/paddle/client";
import { trackEvent } from "@/lib/analytics";

export function PricingCards(){const [selected,setSelected]=useState<PricingPlan|null>(null);return <><div className="pricing-grid">{pricingPlans.map((plan,index)=><article className={`price-card ${plan.popular?"popular":""}`} key={plan.key} style={{animationDelay:`${index*70}ms`}}>{plan.popular&&<span className="popular-tag">Most popular</span>}<div><h3>{plan.name}</h3><p><strong>{plan.displayPrice}</strong><span>/month</span></p><small>{plan.setupDisplay}</small></div><ul>{plan.features.map(feature=><li key={feature}>✓ {feature}</li>)}</ul>{plan.salesOnly?<Link className="button button-secondary" href="/book-demo">{plan.cta}</Link>:<button className="button button-primary" onClick={()=>{setSelected(plan);trackEvent("plan_selected",{plan:plan.key})}}>{plan.cta}</button>}</article>)}</div>{selected&&<CheckoutDialog plan={selected} close={()=>setSelected(null)}/>}</>}

function CheckoutDialog({plan,close}:{plan:PricingPlan;close:()=>void}){const [terms,setTerms]=useState(false);const [recurring,setRecurring]=useState(false);const [status,setStatus]=useState<"idle"|"loading"|"error">("idle");const missing=!plan.monthlyPriceId||!plan.setupPriceId;
 async function checkout(){if(!terms||!recurring)return;setStatus("loading");const paddle=await getPaddle();if(!paddle||missing){setStatus("error");return;}trackEvent("checkout_started",{plan:plan.key});paddle.Checkout.open({items:[{priceId:plan.monthlyPriceId!,quantity:1},{priceId:plan.setupPriceId!,quantity:1}],settings:{displayMode:"overlay",theme:"light",locale:"en",successUrl:`${window.location.origin}/checkout/success`},customData:{plan:plan.key,termsAcceptedAt:new Date().toISOString(),termsVersion:"2026-08-29"}});setStatus("idle")}
 return <div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="checkout-dialog" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><button className="dialog-close" onClick={close} aria-label="Close checkout">×</button><span className="section-kicker">Secure Paddle checkout</span><h2 id="checkout-title">Start with {plan.name}</h2><div className="order-line"><span>{plan.name} plan<small>Recurring monthly</small></span><b>{plan.displayPrice}/mo</b></div><div className="order-line"><span>Implementation<small>One-time setup</small></span><b>{plan.setupDisplay.replace("from ","")}</b></div><div className="order-total"><span>Due today</span><strong>Calculated securely by Paddle</strong></div><p className="checkout-note">Taxes and the exact total are calculated in Paddle Checkout using your location and catalog prices.</p><label className="check"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>I agree to the <Link href="/terms">Terms of Service</Link> and acknowledge the <Link href="/privacy">Privacy Policy</Link>.</span></label><label className="check"><input type="checkbox" checked={recurring} onChange={e=>setRecurring(e.target.checked)}/><span>I authorize the recurring subscription shown above until canceled under the <Link href="/cancellation">Cancellation Policy</Link>.</span></label>{missing&&<p className="notice">Paddle Sandbox catalog IDs are not configured yet. Follow docs/PADDLE_SETUP.md before testing checkout.</p>}{status==="error"&&<p className="form-error" role="alert">Secure checkout is unavailable. Verify the Sandbox token and price IDs, then try again.</p>}<button className="button button-primary checkout-submit" disabled={!terms||!recurring||status==="loading"} onClick={checkout}>{status==="loading"?"Opening secure checkout…":"Continue to Secure Checkout"}</button><small className="paddle-note">Payment details are collected and processed by Paddle. MateAI never handles card numbers.</small></section></div>}
